spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgresDB}
    username: ${DB_USERNAME:username}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        globally_quoted_identifiers: true
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B1987
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days